---
title: "Teaching Statistics with R in Psychology Symposium"
author: "Department of Psychology, Nottingham Trent University"
date: "Thursday, 23 June, 2022."
output:
  html_document: default
  github_document: default
abstract: |
  Statistical data analysis has always been a major part of the undergraduate and postgraduate curriculum in the field of psychology. In the last few decades, the principal software that has been most widely used for teaching statistics in psychology has been SPSS. More recently, given the increasing popularity and widespread use of R, many psychology departments have switched their teaching software from SPSS to R. The purpose of this online symposium is to bring together representatives from psychology departments in the UK who now teach statistics using R in order to discuss the practicalities, challenges, and opportunities of teaching with R. We will have talks from representatives of Lancaster University, Nottingham Trent University, University of Glasgow, the University of Plymouth, and the University of Sussex.
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```



# Programme

## The challenges and successes of teaching using R in a large department. *Russell Turk, Lucy Justice, Nottingham Trent University*.

In 2019, the Department of Psychology in Nottingham Trent University began its transition from SPSS to R for all statistics and research methods teaching. We completed this transition this year. Each year, we now teach statistics and research methods, including research projects, using R to 2,500 undergraduate students and this involves over 150 members of staff.  In this talk, I will discuss the practical and other challenges we encountered in this transition, what worked well, what did not work well, and our plans for the future. [Slides](slides/r-turk-R_symposium_talk.pptx)

<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/IlkQF8pnKhA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>


## From SPSS to R in Undergraduate Psychology. *Andy Wills, University of Plymouth*.

In 2018, the School of Psychology at the University of Plymouth began teaching R to all new undergraduates. We're a typical School in terms of entry grades. So, if our students can handle learning R, yours probably can, too. Our first cohort of students taught R graduated in 2021. They were taught R throughout all three years of the programme. And, in their final project, almost 90% of students primarily used R. In many cases, the work they produced was impressive. In this talk, I'll outline how we made this transition, what we learned, and give some suggestions about how to achieve a similar transition in other UG psychology programmes. [Slides](slides/andy-wills-spss-to-r.pdf)
 
<div align='center'>
<iframe width="560" height="315" src="https://youtube.com/embed/MUX4ZyeH3y0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>

## `#PsyTeachR`: Teaching robust and reproducible research methods. *Helena Paterson, James Bartlett, University of Glasgow*.

At the University of Glasgow, we redesigned our Psychology undergraduate and postgraduate teaching to focus on robust and reproducible methods. Our research methods curriculum now promotes students’ independence in their research practice by emphasizing traditionally overlooked skills, including data wrangling, visualisation, and dynamic reports. We had to make wholesale changes to our practical teaching to allow these developments, such as moving to a coding-based approach through R and associated packages. In the process, we developed in-house online textbooks, tools, and assessments. In this session, we will share our rationale, experiences, and tools with the added perspective of a new team member and how they have adjusted to teaching the established curriculum.
[Slides](slides/h-patterson-NTU_R_Teaching.pptx)

<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/8LVT5AsjDJE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>

## The practicalities of using the RStudio Server for teaching R. *Tom Beesley, Lancaster University*.

In this talk I will provide a rationale for adopting the RStudio Server, which allows students an easy route into using RStudio using only a web browser. I will discuss the process of setting this up, the tasks needed to administer the server, and the benefits for students and staff.
[Slides](slides/RStudio_Server_NTU_Beesley.pptx)

<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/ehjM-om7U1Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>

## Perceived barriers to learning R/RStudio amongst social science faculty. *Jenny Terry, University of Sussex*.

Teaching staff at a UK university who had recently undergone introductory R/RStudio training took part in group interviews that explored their experiences of learning R/RStudio and how they thought their students would compare. Inductive analysis indicated that staff felt that motivation was the key to overcoming the R/RStudio learning curve and that self-efficacy, perceived value, accountability, and anxiety management were important in fostering and maintaining motivation. Participants agreed that building opportunities to strengthen these factors into undergraduate R/RStudio teaching would be crucial for student success. Potential challenges and opportunities for application will be discussed.
[Slides](slides/j_terry_teaching_r_symposium.pptx)

<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/RbPh8Jf7DAM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>


## Student and staff reflections on the undergraduate learning and teaching of R. *Emma Mills, Lancaster University*.

Lancaster University Psychology is in its second year of teaching undergraduate statistics through R and RStudio. We are involved in the National Data Skills Pilot run by the Office for Students which has afforded us an opportunity to conduct some in-house research to reflect on this method.  In this talk I will present an overview of the themes arising from student and teaching staff focus groups, a survey of the wider psychology staff responses to the change and student attainment in statistics assessment.
[Slides](slides/EmmaMills_TeachR.pptx)

<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/X9VaH-_Pg94" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>


## Tipping the SCALES: Expectations and Reality of Statistics Learning. *Jennifer Mankin, Luise Kalus, University of Sussex*.

Students learning statistics, particularly in non-STEM fields, face numerous challenges: maths anxiety, new coding languages, and practical applications within their field – challenges that can have far-reaching consequences for their academic success and their future careers. In this talk we will present some key findings from our longitudinal study, SCALES (Statistics, Coding Attitudes, and Learning Experiences Survey) with undergraduate psychology students learning R at the University of Sussex. We discuss both qualitative findings about students’ expectations and goals for their learning, and statistical results investigating attitudes towards statistics and coding in relation to attainment.

<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/x-FN0d55mJA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>



## General discussion


<div align='center'>
<iframe width="560" height="315" src="https://www.youtube.com/embed/SEt0mEH8uy4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>
</div>
